### PR TITLE
Embed step arguments in json output

### PR DESCRIPTION
**Pull request by J-Ben87**
This might be usefull when testing an API for instance.

Use case:
```gherkin
Feature:
    Scenario:
        Given I prepare a "POST" request on "/api/users" with body:
        {
            "username": "john.doe"
        }
        When I send the request
        Then I sould receive a 201 response containing the following json:
        """
        {
            "id": 1,
            "username": "john.doe"
        }
        """
```

### CODE REVIEW

**Comment by J-Ben87** [comment]
Hi,
Thanks for your work, it's very helpful.
Could you please merge this PR (or give me feedback)? I need it for my project :)

**Comment by J-Ben87** [comment]
Thank you!
Last thing so that I can use it: could you create a release and publish it on packagist please?

**Comment by mytord** [comment]
No problem, new tag was added

**Comment by J-Ben87** [comment]
I'm sorry but it seems that it was not published on packagist, which mean that it cannot be pulled from composer :(

**Comment by J-Ben87** [comment]
Thanks a lot!

**Comment by suswari** [comment]
Hi @J-Ben87,
If the fix cannot be pulled from composer, can you please suggest how can I use the fix.
Thanks!!

**Comment by J-Ben87** [comment]
Hi,
Sorry for the late answer, it can be pulled since my last answer, you should use the `1.1.3` version from https://packagist.org/packages/vanare/behat-cucumber-json-formatter

**Pull request merged**
